### ISSUE TITLE
`pipestat_project_name` parameter to manager constructor is currently unused

### ISSUE THREAD

**Issue by vreuter** [databio/pypiper#213]
Is this a known issue? What's its intended use?

**Comment by donaldcampbelljr** [comment]
Yeah, it appears as though it was left in there after a pipestat refactor. In pipestat we unified records to be `record_Identifier` instead of having either `sample_name` or `project_name`.

We should also rename `pipestat_sample_name` to `pipestat_record_identifier` for consistency:
https://github.com/databio/pypiper/blob/3a8465a900f15a023afc2dd0b73e30cbf2e7eb24/pypiper/manager.py#L332-L334

**Comment by donaldcampbelljr** [comment]
Ok, this should be addressed now. I also noticed some of the values were missing from the doc strings so added them as well.
