### ISSUE TITLE
pypiper function to add sample attributes

### ISSUE THREAD

**Issue by nsheff** [databio/pypiper#23]
Just brainstorming a bit here...Pypiper should enable you to add attributes to a sample; and then it could write the sample object (as a sample yaml) at the end of the pipeline run.

Andre I think your classes accomplish this, but right now there's no explanation or documentation of how people can do that.

Also right now, your pipelines have to import looper, which is not ideal...
```
from looper.models import AttributeDict, Sample
```

What if we added the generic sample object to Pypiper?

**Comment by afrendeiro** [comment]
One can at any time add attributes to the sample object and simply call `Sample.to_yaml()` (which takes an optional path argument) to save it.

Of course this would imply importing looper.models.Sample or optionally implementing some other way of accessing the Sample objects inside the pipeline run, which was why in my initial implementation I preferred using pickle over yaml for sample serialization which allowed the use of the exact same object without importing anything additionally. I still prefer yaml now.
On the other hand, importing modules is just the way modular software was meant to be used, we probably should just embracing it.

I think we can no longer make an argument favoring simplicity mostly by reducing the number of dependencies since we developed three packages that can all work separately but in practice were meant to work together - it is just normal that we face cases where we have to cross-import them at several times.

Additionally, I don't see moving Sample objects over to pypiper as very coherent with the initial philosophy: pypiper was supposed to be about running commands (and providing pre-built commands to run with NGSTk) and looper about managing several input samples and distributing them across pipeline jobs.

**Comment by nsheff** [comment]
I agree.

I don't want to not *allow* the cross-module communication... just not *require* it, to keep things modular.

Actually this is conceptually leading me to an idea I think I proposed earlier: the models really belong in yet a third module. pipelines that need them could import that. looper would also import it. This starts to connect with the point in issue #18 -- where  you want something that doesn't use looper but does use models; or doesn't use pypiper but does use NGSTk. Maybe we need to think about further divisions.

**Comment by nsheff** [comment]
This basically came up again as #57.

**Comment by vreuter** [comment]
I don't quite understand what would need done here...can you provide a hypothetical signature and/or sample code usage pattern? It doesn't seem like the import of `Sample` would be needed--just knowledge of how to update one.

**Comment by nsheff** [comment]
I think maybe nothing... just saying:

sample.attribute = blah

will that work? and then show up in the output sample yaml?

I think it's mostly just a question at this point about establishing the idiom for how to do this. Keep in mind this issue is from 2016...

**Comment by vreuter** [comment]
> I think maybe nothing... just saying:
> 
> sample.attribute = blah
> 
> will that work? and then show up in the output sample yaml?

Yeah that's what I'm suggesting. The "diff" that would constitute the post-hoc YAML would then be things so "attached to" or "stored in" the sample during processing, or KV pairs for which the key was present at the start but the value changed.

Or we could spill everything--including unchanged KV pairs--to disk. I don't really have a preference but think we should decide before implementing.

**Comment by nsheff** [comment]
I'd prefer everything at this point.

Maybe one other thing to keep in mind is the `outputs` specified by the pipeline interface file... these should definitely be sample attributes in the post-analysis yaml file... that's probably preferred over doing something like `sample.attribute` in the pipeline... but I guess either should work.

**Comment by vreuter** [comment]
"Everything" sounds to me in conflict with considering some specific pool of keys (`outputs`). If we're including "everything," then no consideration of `outputs` will be made--an `output` will either have been included during processing, or it won't have been.

**Comment by vreuter** [comment]
https://github.com/pepkit/looper/issues/201
