### ISSUE TITLE
Returning self.name seems wrong here?

### ISSUE THREAD

**Issue by rrauenza** [databio/pypiper#68]
I was considering writing my own one of these .. so was reviewing how yours works.  These two lines seem suspect ... self.name isn't the same as `self.__dict__[name]` ...

https://github.com/databio/pypiper/blob/3097266ad915ea0a9be6081b4487053fda0c5a73/pypiper/AttributeDict.py#L46-L47

Perhaps I don't understand, but I thought you might want to take a second look.

**Comment by nsheff** [comment]
well, that's exactly how it works... it's trying to convert the dict-style accessor into an attribute-style accessor. The point is that for these objects, they should be the same.

So I can say: `object.attribute` or `object["attribute"]` (equivalent to `object.__dict__['attribute']`) and it will give the same thing.

You might want to have a look at a more recent version here: 

https://github.com/pepkit/peppy/blob/master/peppy/attribute_dict.py

**Comment by vreuter** [comment]
Frankly, I was sort of alarmed when I saw this initial message and the code in question; I was surprised that this works. The reason that it looks strange/suspect to me is because it seems like `return self.name` would be equivalent to `self.__getattr__(self, "name")`. Is that what you also were thinking @rrauenza ?

I think that this is used for a key class or two, so I figured it couldn't be as it seemed. And indeed, with a toy class in an interpreter with this same sort of code, I do get the behavior that's intended here. It still feels quirky to me, but it seems to work.

```
In [1]: class Tester(object):
   ...:     def __init__(self):
   ...:         super(Tester, self).__init__()
   ...:     def __getattr__(self, name):
   ...:         if name in self.__dict__.keys():
   ...:             return self.name
   ...:         

In [2]: t = Tester()

In [3]: t.name

In [4]: t.a

In [5]: t.a = 1

In [6]: t.a
Out[6]: 1
```

**Comment by vreuter** [comment]
Is the eventual idea still to have `pypiper` use the `AttributDict` in `peppy` that you referenced @nsheff ? I think at one point we discussed a difference in preference, based on most frequent usage patterns, between `looper` and `pypiper` for the `_attribute_identity` setting? That may've been something slightly different, though.

**Comment by nsheff** [comment]
If I remember correctly, I think it works because of the way python stores attributes; under the hood, the object is actually a dict, with attributes as the keys in that dict. So saying `t.name` is effectively pulling the `name` key out of the `__dict__` dict, which is just the object representation.

Anyway I agree that it looks quirky and your updates in `peppy` are better, @vreuter -- Yes, the goal was for all of these to use a single version of it; for now `pypiper` could import `peppy`, or we could make a new package for the attributedict and have them both import it. It's the `default` attribute that was a bit different, but as along as the combined version can support either, there's no reason not to share

**Comment by vreuter** [comment]
Oh, I think @rrauenza is right and that this line is actually not as we intend, but it just doesn't become an issue since this `return self.name` is never touched. Satisfaction of the condition would imply that `__getattribute__` would've returned a value rather than calling into `__getattr__`, since we've not also overridden `__getattr__`. So we should probably drop the outer if/else and move the block within the outer `else` out/up a level. So something like this should be equivalent:
```
if self.return_defaults:
    return name
raise AttributeError("No attribute: " + name)
```

**Comment by vreuter** [comment]
It looks to me like the first conditional is in fact hit in neither the *key-absent* nor the *key-present* case:

```
In [15]: class Tester(object):
    ...:     def __init__(self, retdef):
    ...:         super(Tester, self).__init__()
    ...:         self.return_defaults = retdef
    ...:     def __getattr__(self, name):
    ...:         if name in self.__dict__:
    ...:             print("Found '{}'".format(name))
    ...:             return self.__dict__[name]
    ...:         else:
    ...:             if self.return_defaults:
    ...:                 return name
    ...:             raise AttributeError("No attribute: " + name)
    ...:         

In [16]: 

In [16]: tRD = Tester(True)

In [17]: tRD.value
Out[17]: 'value'

In [18]: tRD.value = 1

In [19]: tRD.value
Out[19]: 1

...

In [23]: tND = Tester(False)

In [24]: tND.value
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-24-463daaa166b1> in <module>()
----> 1 tND.value

<ipython-input-15-a01b3dd6145a> in __getattr__(self, name)
     10             if self.return_defaults:
     11                 return name
---> 12             raise AttributeError("No attribute: " + name)
     13 

AttributeError: No attribute: value

In [25]: tND.value = 1

In [26]: tND.value
Out[26]: 1
```

**Comment by vreuter** [comment]
But I guess if the idea is to share the same `AttributeDict` between `pypiper` and `looper`, via `peppy`, then this is less consequential.

**Comment by rrauenza** [comment]
Right ... what I mean is that `'name' is in __dict__.keys()` isn't the same `name in __dict__.keys()` and only the former might be the same as `self.name`....

**Comment by vreuter** [comment]
`"name" is in __dict__.keys()` is illegal syntax I think? What do you mean there?

**Comment by rrauenza** [comment]
yeah, fixed [above](https://github.com/databio/pypiper/issues/68#issuecomment-368100195).

But what you said [above ](https://github.com/databio/pypiper/issues/68#issuecomment-364329455) is what I was trying to say.   i.e., 

Are we trying to return `__dict__[name]` or  `self.__dict__['name']`.   IOW, is the string `'name'` the key, or is the value held within the variable `name` the key.

**Comment by vreuter** [comment]
Ah OK, got it. Yes, the idea is to return `__dict__[name]` (i.e., the key is the *value* of `name`). Does the idea about `__getattribute__` seem reasonable? I think that's why this is not being hit, since--as you point out--this would not return the correct value.

**Comment by nsheff** [comment]
hey @rrauenza you might want to check out [attmap](https://pypi.org/project/attmap/) which we've now spun off into a separate project.
