### ISSUE TITLE
get_parameter name

### ISSUE THREAD

**Issue by nsheff** [databio/pypiper#71]
The new `get_parameter` function is really useful. But I think it should have a different name... that's very generic. something that conveys the hierarchical behavior.

maybe, `get_cascading_parameter` or something?

**Comment by vreuter** [comment]
Yikes, I should've filled out that docstring! https://github.com/databio/pypiper/blob/master/pypiper/utils.py#L266
Yeah, it should have a more descriptive name. `get_cascading_parameter` sounds fine, though to me it sort of suggests that the _parameter_ being sought will have a "cascade" of consequences/implications, rather than that the search "cascades" through the pool of maps.
I'm all good w/ the cascade naming, but I also like something like `find_first_parameter` or even `find_first_value` to reflect the fact that the parameter name could be in multiple maps, but it will be its value from the one in which it's first found that will be returned.

**Comment by nsheff** [comment]
do you happen to know where this is used? I didn't actually see it used anywhere...

**Comment by vreuter** [comment]
Yeah it doesn't look like it's used in this project, and I checked a few of the pipeline repositories that seemed like candidates but didn't see it there either. I think maybe the idea was to have it in place for supporting prioritized configuration parsing, like from command-line vs. project-specific pipeline config vs. general/base pipeline config, but I guess it's not been used.

**Comment by nsheff** [comment]
See https://github.com/databio/rnapipe/issues/8
