### ISSUE TITLE
arguments are added in strange order

### ISSUE THREAD

**Issue by nsheff** [databio/pypiper#75]
The new `_determine_args` functions are adding arguments haphazardly, instead of according to the order in which they are listed.

**Comment by vreuter** [comment]
Yeah it looks like most of the logic there is using sets and maps rather than respecting order. Do you have a quick use case that's an example of the unexpected behavior?

**Comment by nsheff** [comment]
what do you think of that?

Well, just in any pipeline, the arguments are just in random order; for example, "input1" is not right next to "input2", and "input2" is the first argument listed in help.

This commit solved it for my test case...

**Comment by vreuter** [comment]
Yeah that looks good to me. This is a corner case, but what happens if you pass in a `None` for the `argument_groups` now, though? I with the existing version this may be protected but may hit a `TypeError` when iterating over the groups in `for g in groups`? That looked possible but did not test it. Also since the function is protected, that seems like this a nonissue if the calling function provides no way for a `None` to be passed in. Anyway, likely not a big deal, but that's the one thing I noticed that seemed like it could come up and behave differently than before.

**Comment by vreuter** [comment]
Ah, yeah that makes sense. Cool yeah looks good -- totally makes sense to put these in a logical ordering especially since it becomes user-facing.
